name = "createwith-invoice-worker"
main = "src/invoice-worker.js"
compatibility_date = "2024-11-22"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
account_id = "1cec23b3da967c4a89800769b5cfa94a"

[browser]
binding = "BROWSER"

[observability]
enabled = true
